---
title: "신호 생성과 검증"
output: github_document
---

```{r message=FALSE, error=FALSE, warning=FALSE}
require(quantmod)
require(xts)
getSymbols("SPY")
getSymbols("AAPL")
```


```{r}
# 이동할 거래일 수
window_length <- 10

# 시간 구간
start_date <- "2011-01-01"
end_date <- "2011-12-31"
range <- paste(start_date, "::", end_date, sep="")

# 주가 쌍
x <- SPY[range, 6]
y <- AAPL[range, 6]

dF <- cbind(x, y)
names(dF) <- c("SPY", "AAPL")

x <- 1:5
test <- coef(lm(c(1:3, 7, 6) ~ x))
class(test)
names(test) <- c("b", "a")
str(test)

# Beta
run_regression <- function(dF) {
  data <- as.data.frame(dF)
  result <- coef(lm(data[,2] ~ data[,1]))
  # return (result)
  names(result) <- c("intercept", "beta")
  return (result)
}

rolling_beta <- function(z, width) {
  rollapply(z, width=width, FUN = run_regression, by.column = FALSE, align = "right")
}

betas <- rolling_beta(diff(dF), 10)

data <- merge(betas, dF)
# data <- na.omit(data)

data$spread <- data$AAPL - lag(data$beta, 1) * data$SPY

# 수익률
returns <- diff(dF) / dF
returns_beta <- rolling_beta(returns, 10)
data$spreadR <- (diff(data$AAPL) / data$AAPL) - returns_beta$beta * (diff(data$SPY) / data$SPY)
tail(data)
```

중심이 0이라고 가정한 스프레드의 평균 대비 위로 1 표준편차, 아래로 1표준편차를 같이 그린 그래프
```{r}
threshold <- sd(data$spread, na.rm = TRUE)
mean <- mean(data$spread, na.rm = TRUE)
plot(data$spread, main = "AAPL vs. SPY In-Sample")
abline(h =  threshold, lty = 2)
abline(h =  mean, lty = 4, col = "red")
abline(h = -threshold, lty = 2)
```

전략 시뮬레이션
* 한 번의 스프레드에 대해 오직 하나의 매수나 매도 포지션을 가져간다
* 스프레드 하나를 매수하고 있는데 매수 신호가 생기면 더 매수하지 않는다
* 포지션을 뒤바꿀 매도 신호를 기다린다
```{r}
# 샘플 밖 스프레드 생성
# 10일 변동 구간 유지
window_length <- 10

# 시간 범위
start_date <- "2012-01-01"
end_date <- "2013-12-31"
range <-paste(start_date, "::", end_date, sep = "")

# 주가 쌍
x <- SPY[range, 6]
y <- AAPL[range, 6]

# 두 주가를 행렬로 묶기
dF <- cbind(x, y)
names(dF) <- c("SPY", "AAPL")

# 샘플 밖 변동 스프레드 계산
beta_out_of_sample <- rolling_beta(diff(dF), 10)

# 매수, 매도 임계치
data_out <- merge(beta_out_of_sample, dF)
data_out$spread <- data_out$AAPL - lag(beta_out_of_sample$beta, 1) * data_out$SPY

# 샘플 안 스프레드 폭과 함께 스프레드 그리기
plot(data_out$spread, main = "AAPL vs. SPY out of sample")
abline(h =  threshold, lwd = 2)
abline(h = -threshold, lwd = 2)
```

트레이딩 로직
```{r}
# 매수, 매도 신호 생성
buys  <- ifelse(data_out$spread >  threshold,  1, 0)
sells <- ifelse(data_out$spread < -threshold, -1, 0)
data_out$signal <- buys + sells
```

매수 신호를 원, 매도 신호를 삼격형
```{r}
plot(data_out$spread, main = "AAPL vs. SPY out of sample")
abline(h =  threshold, lty = 2)
abline(h = -threshold, lty = 2)

buy_index   = which(data_out$signal ==  1)
sell_index  = which(data_out$signal == -1)
point_type  = rep(NA, nrow(data_out))
point_type[buy_index ] <- 21
point_type[sell_index] <- 24
points(data_out$spread, pch = point_type)
```

매수/매도 신호 횟수
```{r}
num_of_buy_signals  <- sum(buys, na.rm = TRUE)
num_of_sell_signals <- sum(abs(sells), na.rm = TRUE)

num_of_sell_signals
num_of_buy_signals
```

X(SPY)와 Y(AAPL)의 거래수량을 계산
```{r}
printf <- function(...)print(sprintf(...))

prev_x_qty <- 0
position   <- 0
trade_size <- 100
signal     <- as.numeric(data_out$signal)
signal[is.na(signal)] <- 0
beta <- as.numeric(data_out$beta)

qty_x <- rep(0, length(signal))
qty_y <- rep(0, length(signal))

for (i in 1:length(signal)) {
  
  # printf('%d, %d', i, position)
  # 초기 스프레드 매수
  if (signal[i] == 1 && position == 0) {
    # SPY 매도량
    prev_x_qty  <- round(beta[i] * trade_size)
    # SPY 매도
    qty_x[i]    <- -prev_x_qty
    # APPL 매수
    qty_y[i]    <- trade_size
    printf('초기 스프레드 매수 SPY=%d, APPL=%d', qty_x[i], qty_y[i])
    position    <- 1
  }
  
  # 초기 스프레드 매도
  if (signal[i] == -1 && position == 0) {
    prev_x_qty <- round(beta[i] * trade_size)
    # SPY 매수
    qty_x[i] <- prev_x_qty
    # APPL 매도
    qty_y[i] <- -trade_size
    position <- -1
    printf('초기 스프레드 매도 SPY=%d, APPL=%d', qty_x[i], qty_y[i])
  }
  
  # 스프레드 매도 상태에서 매수
  if (signal[i] == 1 && position == -1) {
    qty_x[i]    <- -(round(beta[i] * trade_size) + prev_x_qty)
    prev_x_qty  <-   round(beta[i] * trade_size)
    qty_y[i]    <- 2 * trade_size
    position    <- 1
    printf('매도 -> 매수 SPY=%d, APPL=%d', qty_x[i], qty_y[i])
  }
  
  # 스프레드 매수 상태에서 매도
  if (signal[i] == -1 && position == 1) {
    qty_x[i]    <- round(beta[i] * trade_size) + prev_x_qty
    prev_x_qty  <- round(beta[i] * trade_size)
    qty_y[i]    <- -2 * trade_size
    position    <- -1
    printf('매수 -> 매도 SPY=%d, APPL=%d', qty_x[i], qty_y[i])
  }
  
}

data_out$qty_spy <- qty_x
data_out$qty_appl <- qty_y
```

수익곡선
```{r}
# 수익 곡선을 계산할 함수
compute_equity_curve <- function(qty, price) {
  cash_buy  <- ifelse(sign(qty) ==  1,  qty * price, 0)
  cash_sell <- ifelse(sign(qty) == -1, -qty * price, 0)
  position  <- cumsum(qty)
  cumulative_buy  <- cumsum(cash_buy)
  cumulative_sell <- cumsum(cash_sell)
  
  # equity <- cumulative_sell - cumulative_buy + position * price
  equity <- cumulative_sell - cumulative_buy # + position * price
  return(equity)
}

data_out$equity_curve_spy  <- compute_equity_curve(data_out$qty_spy, data_out$SPY)
data_out$equity_curve_appl <- compute_equity_curve(data_out$qty_appl, data_out$AAPL)

plot(data_out$equity_curve_spy + data_out$equity_curve_appl, type = "l", main = "AAPL / SPY spread", ylab = "P&L")

cumsum(data_out$qty_spy) * data_out$SPY

```

```{r}
cumsum(1:10)
```

