---
title: "Untitled"
output: html_document
---

```{r}
require(xts)
require(data.table)
orders <- read.csv("orders.csv")
orders[,1] <- as.POSIXct(orders[,1]/1000, origin = "1970-01-01")
orders[,2] <- as.factor(orders[,2])
orders[,3] <- as.numeric(orders[,3])
orders[,4] <- as.numeric(orders[,4])
orders[,5] <- list(total=orders[,3] * orders[,4])

orders.table <- data.table(orders)
# orders[, lapply(.SD, mean), by=list(date, order)]
# orders[, list(unit=mean(unit), qty=sum(qty)), by=list(date, order)]
# orders.table[, list(avg=(unit * qty)), by=list(date, order)]
orders.avg.ask <- orders.table[order=='ask', list(avg=(sum(total) / sum(qty))), by=list(date, order)]
orders.avg.bid <- orders.table[order=='bid', list(avg=(sum(total) / sum(qty))), by=list(date, order)]

# plot ask and bid
{
plot(x=orders.avg.ask$date, y=orders.avg.ask$avg, type='l', col='red')
lines(x=orders.avg.bid$date, y=orders.avg.bid$avg, type='l', col='blue')
}

```

```{r}
require(xts)
require(data.table)
transactions <- read.csv("tsx.csv")
transactions[,1] <- as.POSIXct(transactions[,1]/1000, origin = "1970-01-01")
transactions[,5] <- list(total=transactions[,3] * transactions[,4])

transactions.table <- data.table(transactions)
transactions.avg <- transactions.table[, list(avg=(sum(total) / sum(qty))), by=list(date)]

diff <- as.data.frame(list(date=orders.avg.ask$date, diff=orders.avg.ask$avg - orders.avg.bid$avg))
diff.mean <- mean(diff$diff)

transaction.median <- median(transactions.avg$avg)
# plot ask and bid
{
par(mar=c(5, 5, 4, 6) + 0.1)
plot(x=transactions.avg$date, y=transactions.avg$avg, type='l')
lines(x=orders.avg.ask$date, y=orders.avg.ask$avg, type='l', col='red')
lines(x=orders.avg.bid$date, y=orders.avg.bid$avg, type='l', col='blue')
lines(x=orders.avg.bid$date, y=diff$diff + transaction.median, type="l", pch=15, col="green")
abline(h=transaction.median)
abline(h=diff.mean + transaction.median)
# lines(x=orders.avg.bid$date, y=diff$diff, type='l', col='yellow')
#par(new = T)
#plot(x=orders.avg.bid$date, y=diff$diff, type="l", pch=15, col="green", xlab=NA, ylab=NA , bty = "n", axes = FALSE)
#abline(h = 0, v = 0, col = "gray60")
}


```


```{r}
# Quantity Analisys

```


